Global:
  device: gpu
  epoch_num: 500
  log_smooth_window: 50
  print_batch_step: 100
  output_dir: outputs/vit_parseq2/
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 500]
  save_epoch_step: [15, 9999]
  cal_metric_during_train: False
  pretrained_model: outputs/vit_parseq/best.pth
  checkpoints: outputs/vit_parseq/last.pth
  use_tensorboard: False
  infer_img: data/data_raw/UIT_HWDB_word/train_data/1
  # for data or label process
  character_dict_path: &character_dict_path data/character_dict/uit_hwdb_word.txt
  max_text_length: &max_text_length 15
  use_space_char: &use_space_char False
  use_amp: True
  save_res_path: outputs/vit_parseq/predicts_vit_parseq.txt
  grad_clip_val: 20

Optimizer:
  name: AdamW
  lr: 0.001485 # 2gpus 384bs/gpu
  weight_decay: 0.
  filter_bias_and_bn: False

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 5 # pct_start 0.075*20 = 1.5ep
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: PARSeq
  Transform:
  Encoder:
    name: ViT
  Decoder:
    name: PARSeqDecoder
    decode_ar: True
    refine_iters: 0

Loss:
  name: PARSeqLoss

PostProcess:
  name: ARLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric
  main_indicator: acc
  is_filter: False

Train:
  dataset:
    name: LMDBDataSet
    data_dir: data/data_lmdb/train
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      # - PARSeqAug:
      - ARLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecTVResize:
          image_shape: [64, 192]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 50
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: data/data_lmdb/test
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - ARLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecTVResize:
          image_shape: [64, 192]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 20
    num_workers: 2
